<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="FB_HwRefDiluter" Id="{727b2819-518c-4c5e-9c6b-f756216b1c19}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HwRefDiluter
VAR_INPUT
	bIsInit 		: BOOL;
	bBusy			: BOOL;
	eValveType 		: E_DilValveType;
	nActValvePos	: SINT;
	nActPlungerPos	: UINT;	
END_VAR
VAR_OUTPUT
	nChannel		: USINT;
END_VAR
VAR
END_VAR
VAR_STAT
	nHighestChannel : USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{995e1476-433c-46e6-a922-2e154939e04c}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[nHighestChannel := nHighestChannel + 1;
nChannel := nHighestChannel;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_HwRefDiluter">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_HwRefDiluter.FB_init">
      <LineId Id="7" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>