<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Cartridge" Id="{b5a93d8b-1f56-4962-aae7-5107faba618a}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Cartridge EXTENDS FB_PieceBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{643afb72-2420-4c09-9525-1f178a1636d0}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[eObjectType := E_ObjectType.OBJECTTYPE_Cartridge;
eObjectGroup := E_ObjectGroup.OBJECTGROUP_Piece;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Cartridge">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cartridge.FB_init">
      <LineId Id="7" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>