<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_pHElectrodeCap" Id="{4a3f5242-be83-4670-a138-0118305bfb8a}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_pHElectrodeCap EXTENDS FB_PieceBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{29d60f44-a8c7-42c3-8fbd-143ccb49c282}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[eObjectType := E_ObjectType.OBJECTTYPE_pHElectrodeCap;
eObjectGroup := E_ObjectGroup.OBJECTGROUP_Piece;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_pHElectrodeCap">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_pHElectrodeCap.FB_init">
      <LineId Id="7" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>