<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Port" Id="{dcab4046-4499-4da6-acf3-5c3875d6f49e}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_Port EXTENDS FB_PieceBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{0d604b1b-609c-4871-abd7-b7f167c48969}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[eObjectType := E_ObjectType.OBJECTTYPE_Port;
eObjectGroup := E_ObjectGroup.OBJECTGROUP_Piece;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Port">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Port.FB_init">
      <LineId Id="7" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>