<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_VialClosed" Id="{8467fa84-e9b8-4ae2-a3e2-0b46b3f86b50}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK FB_VialClosed EXTENDS FB_Vial
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{56f299d8-ac98-4538-9a5a-fb0e8eb758c0}">
      <Declaration><![CDATA[{attribute 'object_name' := 'FB_init'}
METHOD FB_init : BOOL
VAR_INPUT
	/// if TRUE, the retain variables are initialized (warm start / cold start)
	bInitRetains: BOOL;
	/// if TRUE, the instance afterwards gets moved into the copy code (online change)
	bInCopyCode: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[eObjectType := E_ObjectType.OBJECTTYPE_VialClosed;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_VialClosed">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_VialClosed.FB_init">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>